mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.outsider.masterofprediction.dto

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
  redirect:
    uri: ${GOOGLE_REDIRECT_URI}

spring:
  application:
    name: master-of-prediction
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    contentnegotiation:
      media-types:
        svg: image/svg+xml
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 2MB
#      max-request-size: 2MB

default_image: logo2.png
file:
  tierImgUrl: images/tier

logging:
  level:
    org:
      springframework:
        security:
            authentication: DEBUG
            web:
              authentication:  DEBUG
server:
  error:
    path: /error