name: Copy Incomplete Issues to Next Iteration

on:
  schedule:
    - cron: '50 10 * * *' # 매월 1일 00:00에 실행 (필요에 따라 수정 가능)

jobs:
  copy_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy incomplete issues to next iteration
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 현재 iteration 레이블
          current_label="iteration:current"
          next_label="iteration:next"
          
          # 미완료 이슈 목록 가져오기
          issues=$(gh issue list --state open --label $current_label --json number,title,body,labels --jq '.[] | @base64')

          for issue in $issues; do
            _jq() {
              echo ${issue} | base64 --decode | jq -r ${1}
            }

            # 이슈 정보 추출
            issue_number=$(_jq '.number')
            issue_title=$(_jq '.title')
            issue_body=$(_jq '.body')
            issue_labels=$(echo $(_jq '.labels | map(.name) | @csv') | sed 's/,/ /g')

            # 새로운 이슈 생성
            new_issue=$(gh issue create --title "$issue_title" --body "$issue_body" --label "$next_label $issue_labels")

            # 기존 이슈에 코멘트 추가
            new_issue_number=$(echo $new_issue | grep -oP '#\K\d+')
            gh issue comment $issue_number --body "이 이슈는 다음 iteration으로 복사되었습니다. 새 이슈 번호: #$new_issue_number"
          done
